name: wechat_camera_picker_demo
description: A new Flutter project.
version: 4.2.1+33
publish_to: none

environment:
  sdk: ^3.2.0
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: '>=0.17.0 <1.0.0'

  wechat_camera_picker:
    path: ../

  package_info_plus: ^5.0.0
  video_player: ^2.7.0

  wechat_picker_library:
    git:
      url: git@github.com:flutting/flutter_wechat_picker_library.git
      ref: flutter3.19/1.0.0

  photo_manager_image_provider:
    git:
      url: git@github.com:flutting/flutter_photo_manager_plugins.git
      ref: flutter3.19/2.0.0
      path: packages/photo_manager_image_provider

  photo_manager:
    git:
      url: git@github.com:flutting/flutter_photo_manager.git
      ref: flutter3.19/3.0.0

dev_dependencies:
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - assets/
